### ISSUE TITLE
Documentation Examples

### ISSUE THREAD

**Issue by pradoz** [aws-samples/parallelcluster-cdk#1]
Hello!

I would like to experiment with this CDK construct and contribute.

How test and verify that the ParallelCluster is performing as expected?

**Comment by ChrisDowning** [comment]
Hi @pradoz - please refer to the "Setup" instructions in the readme to understand how to deploy this CDK app, then check out the [ParallelCluster documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/what-is-aws-parallelcluster.html) to learn about the cluster configuration.

To check on the status of the cluster after deployment, you can look at the stacks in the CloudFormation console. Assuming there were no issues in the deployment process, you should have an EC2 instance running which serves as the cluster head node - you can connect to this via SSH (or Systems Manager if you left the `AmazonSSMManagedInstanceCore` additional IAM policy in place).

Another thing to note is that this repository contains a CDK [app](https://docs.aws.amazon.com/cdk/v2/guide/apps.html), not a [construct](https://docs.aws.amazon.com/cdk/v2/guide/constructs.html). There is currently no CDK construct for ParallelCluster - this app is intended to demonstrate how you can use a [Custom Resource](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.custom_resources/README.html) as an alternative.

**Comment by pradoz** [comment]
Thanks @ChrisDowning, and good point regarding app vs construct.

What are your initial thoughts on replacing OpenZFS/Lustre/EFS with something like [mountpoint-s3](https://github.com/awslabs/mountpoint-s3)?

**Comment by ChrisDowning** [comment]
Hi @pradoz - apologies, I missed your follow-up before.

Mountpoint for S3 could be interesting for some specific scenarios, but there are important differences in how mountpoint-s3 handles file metadata when syncing to S3 compared to the equivalent behaviour in FSx for Lustre. Configuring mountpoint-s3 on a cluster is documented in [this blog](https://aws.amazon.com/blogs/hpc/improve-the-speed-and-cost-of-hpc-deployment-with-mountpoint-for-amazon-s3/), so you can try it for your specific use-case.
